apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sparkclusters.spark.stackable.tech
spec:
  group: spark.stackable.tech
  names:
    kind: SparkCluster
    singular: sparkcluster
    plural: sparkclusters
    listKind: SparkClusterList
    shortNames:
      - sc
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                master:
                  type: object
                  properties:
                    selectors:
                      type: array
                      items:
                        type: object
                        properties:
                          nodeName:
                            type: string
                          instances:
                            type: integer
                          masterPort:
                            type: integer
                          masterWebUiPort:
                            type: integer
                          config:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                          env:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                worker:
                  type: object
                  properties:
                    selectors:
                      type: array
                      items:
                        type: object
                        properties:
                          nodeName:
                            type: string
                          instances:
                            type: integer
                          cores:
                            type: integer
                          memory:
                            type: string
                          workerPort:
                            type: integer
                          workerWebUiPort:
                            type: integer
                          config:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                          env:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                historyServer:
                  type: object
                  properties:
                    selectors:
                      type: array
                      items:
                        type: object
                        properties:
                          nodeName:
                            type: string
                          instances:
                            type: integer
                          storePath:
                            type: string
                          historyUiPort:
                            type: string
                          config:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                          env:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                version:
                  type: string
                secret:
                  type: string
                logDir:
                  type: string
                maxPortRetries:
                  type: integer
            status:
              nullable: true
              properties:
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        description: "lastTransitionTime is the last time the condition transitioned from one status to another. This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable."
                        format: date-time
                        type: string
                      message:
                        description: message is a human readable message indicating details about the transition. This may be an empty string.
                        type: string
                      observedGeneration:
                        description: "observedGeneration represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date with respect to the current state of the instance."
                        format: int64
                        type: integer
                      reason:
                        description: "reason contains a programmatic identifier indicating the reason for the condition's last transition. Producers of specific condition types may define expected values and meanings for this field, and whether the values are considered a guaranteed API. The value should be a CamelCase string. This field may not be empty."
                        type: string
                      status:
                        default: Unknown
                        description: "status of the condition, one of True, False, Unknown."
                        enum:
                          - Unknown
                          - "True"
                          - "False"
                        type: string
                      type:
                        description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        pattern: "^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$"
                        type: string
                    required:
                      - lastTransitionTime
                      - message
                      - reason
                      - status
                      - type
                    type: object
                  type: array
                  x-kubernetes-list-map-keys:
                    - type
                  x-kubernetes-list-type: map
                currentVersion:
                  enum:
                    - 2.4.7
                    - 3.0.1
                    - 3.0.2
                    - 3.1.1
                  nullable: true
                  type: string
                targetVersion:
                  enum:
                    - 2.4.7
                    - 3.0.1
                    - 3.0.2
                    - 3.1.1
                  nullable: true
                  type: string
                currentCommand:
                  type: object
                  properties:
                    commandRef:
                      type: string
                    commandType:
                      type: string
                    startedAt:
                      type: string
                clusterStatus:
                  enum:
                    - Stopped
                    - Running
                  nullable: true
                  type: string
              type: object
      subresources:
        status: { }
