---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: ionos-k8s
metadata:
  name: spark-operator-integration-tests
  description: "Cluster for Spark Operator Integration Tests (IONOS Cloud managed K8s)"
domain: stackable.test
publicKeys: []
spec:
  region: de/fra
  versions:
    _-operator: NIGHTLY
    spark-operator: "$SPARK_OPERATOR_VERSION"
  node_count: 3
