---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: azure-aks
metadata:
  name: spark-operator-integration-tests
  description: "Cluster for Spark Operator Integration Tests (Azure AKS)"
publicKeys: []
spec:
  versions:
    _-operator: NIGHTLY
    spark-operator: "$SPARK_OPERATOR_VERSION"
  node_count: 3
