apiVersion: spark.stackable.tech/v1alpha1
kind: SparkCluster
metadata:
  name: simple-spark
spec:
  version: "3.0.1"
  config:
    enableMonitoring: true
  masters:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config: {}
  workers:
    roleGroups:
      2core2g:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          cores: 2
          memory: "2g"
  historyServers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config: {}

