apiVersion: spark.stackable.tech/v1alpha1
kind: SparkCluster
metadata:
  name: simple
spec:
  version: "3.0.1"
  config:
    logDir: "file:///tmp"
  masters:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/arch: stackable-linux
        replicas: 1
        config:
          masterPort: 7078
          masterWebUiPort: 8081
  workers:
    roleGroups:
      2core2g:
        selector:
          matchLabels:
            kubernetes.io/arch: stackable-linux
        replicas: 4
        config:
          cores: 2
          memory: "2g"
          workerPort: 3031
          workerWebUiPort: 8083
  historyServers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/arch: stackable-linux
        replicas: 1
        config:
          historyWebUiPort: 18081

