apiVersion: spark.stackable.tech/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  master:
    selectors:
      - nodeName: "mdesktop"
        instances: 1
        masterPort: 9999
        masterWebUiPort: 11111
  worker:
    selectors:
      - nodeName: "mdesktop"
        instances: 1
        cores: 1
        memory: "1g"
  historyServer:
    selectors:
      - nodeName: "mdesktop"
        instances: 1
  version: "3.0.1"
  maxPortRetries: 0
