apiVersion: spark.stackable.tech/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  version: "3.0.1"
  masters:
    selectors:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: mdesktop
        instances: 1
        instancesPerNode: 1
        config:
          masterPort: 9999
          masterWebUiPort: 11111
      default2:
        selector:
          matchLabels:
            kubernetes.io/hostname: mdesktop
        instances: 1
        instancesPerNode: 1
        config:
          masterPort: 9998
          masterWebUiPort: 11110
  workers:
    selectors:
      1core1g:
        selector:
          matchLabels:
            kubernetes.io/hostname: mdesktop
        instances: 1
        instancesPerNode: 1
        config:
          cores: 1
          memory: "1g"
      2core2g:
        selector:
          matchLabels:
            kubernetes.io/hostname: mdesktop
        instances: 1
        instancesPerNode: 1
        config:
          cores: 2
          memory: "2g"
  historyServers:
    selectors:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: mdesktop
        instances: 1
        instancesPerNode: 1

