apiVersion: spark.stackable.tech/v1
kind: SparkCluster
metadata:
  name: spark-cluster
spec:
  version: "3.0.1"
  masters:
    selectors:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: mdesktop
        instances: 1
        instancesPerNode: 1
        config:
          masterPort: 9999
          masterWebUiPort: 11111
  workers:
    selectors:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: mdesktop
        instances: 2
        instancesPerNode: 2
        config:
          cores: 1
          memory: "1g"
  historyServers:
    selectors:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: mdesktop
        instances: 1
        instancesPerNode: 1

