[package]
authors = ["Malte Sander <malte.sander.it@gmail.com>"]
description = "Contains utilities for the Stackable Operator for Apache Spark"
edition = "2018"
license = "OSL-3.0"
name = "stackable-spark-common"
version = "0.4.0-nightly"

[dependencies]


